# Sensitive Configuration (Replace with actual values)
apiVersion: v1
kind: Secret
metadata:
  name: media-server-secrets
  namespace: media-server
type: Opaque
data:
  # Database password (base64 encoded)
  DB_PASSWORD: "eW91cl9wYXNzd29yZF9oZXJl"  # Replace with actual base64 encoded password
  
  # JWT secret (base64 encoded)
  JWT_SECRET: "eW91cl9qd3Rfc2VjcmV0X2hlcmU="  # Replace with actual base64 encoded secret
  
  # Email configuration (base64 encoded)
  EMAIL_HOST: "c210cC5nbWFpbC5jb20="  # smtp.gmail.com
  EMAIL_USER: "eW91ckVtYWlsQGdtYWlsLmNvbQ=="  # yourEmail@gmail.com
  EMAIL_PASS: "eW91cl9lbWFpbF9wYXNzd29yZA=="  # your email password
  
  # API keys (base64 encoded)
  TMDB_API_KEY: "eW91cl90bWRiX2FwaV9rZXk="  # Your TMDB API key
  OMDB_API_KEY: "eW91cl9vbWRiX2FwaV9rZXk="  # Your OMDB API key
  
  # Cloudflare API token (base64 encoded)
  CLOUDFLARE_API_TOKEN: "eW91cl9jbG91ZGZsYXJlX2FwaV90b2tlbg=="  # Your Cloudflare API token

---
# SSL Certificate Secret (will be auto-generated by cert-manager)
apiVersion: v1
kind: Secret
metadata:
  name: archiveofobselis-tls
  namespace: media-server
type: kubernetes.io/tls
data:
  # These will be automatically populated by cert-manager
  tls.crt: ""
  tls.key: "" 